language: python
notifications:
  email: false
env:
  global:
    - PSQL=postgres://postgres:@localhost:5432/inquiry
python:
  - 2.7
install:
  - python setup.py install
  - pip install -r tests/requirements.txt
  - psql -c 'create database inquiry;' -U postgres
  - psql inquiry -f tests/demo.sql
script:
  nosetests --rednose --with-cov --cov-config=.coveragerc
after_success:
  codecov
