language: python
notifications:
  email: false
env:
  global:
    - secure: gY09YSq+4lFzAByBmuQhlNpgPF25+kBMCczfiX4CjG4LSNMtNp4QnyL+g6eF\ndobY6ielUBBdX3wioLAP12VawVciCfxfDLxVGACU5wrpoqNyA2NSfHEifC9t\nsuMzkHETJiZU6ZfaD/CFmdAA3Xf0jiXFK80m/xAlRnY+DyWHSLQ=
    - PSQL=postgres://postgres:@localhost:5432/inquiry
services: postgres
python:
  - 2.7
install:
  - python setup.py install
  - pip install coveralls codecov
  - pip install git+git://github.com/stevepeak/tornpsql.git
  - psql -c 'create database inquiry;' -U postgres
  - psql inquiry -f tests/demo.sql
script:
  coverage run -m unittest discover -s tests
after_success:
  coveralls
  codecov
