language: python
notifications:
  email: false
python:
  - 2.7
install:
  - python setup.py install
  - pip install coveralls psycopg2
script:
  coverage run -m unittest discover -s tests
after_success:
  coveralls
