language: python
notifications:
  email: false
python:
  - 2.7
  - pypy
install:
  - python setup.py install
  - pip install coveralls
script:
  coverage run -m unittest discover -s tests
after_success:
  coveralls
