language: python
notifications:
  email: false
env:
  global:
    - PSQL=postgres://postgres:localhost:5432/inquiry
services: postgres
python:
  - 2.7
install:
  - python setup.py install
  - pip install coveralls tornpsql
  - psql -c 'create database inquiry;' -U postgres
  - psql inquiry -f tests/demo.sql
script:
  coverage run -m unittest discover -s tests
after_success:
  coveralls
